highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://jinfuchen.github.io/jinfu
author: jinfu chen

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /jinfu/
title: Bajin
name: Jinfu Chen
email: bajin886@gmail.com
email_full: bajin886@gmail.com
website: homepage
website_full: https://jinfuchen.github.io/jinfu
github: trending
tel: +1 888-888-8888
tel_full: tel:+1-888-888-8888
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address: 44 Perth Street
postcode: EH3 5BL
city: Montreal
country: Canada
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
