highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://jinfuchen.github.io/jinfu
author: jinfu chen

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /jinfu/
title: jinfuchen
name: Jinfu Chen
email: jinfuchen@whu.edu.cn
email_full: jinfuchen@whu.edu.cn
website: homepage
website_full: https://jinfuchen.github.io/jinfu
github: jinfuchen
tel: 514-848-2424
tel_full: tel:+1-514-848-2424
google_maps: 'https://goo.gl/maps/Zick6WmBVyC2'
address: 299 Bayi Road
postcode: H3G 1M8
city: Wuhai, Hubei
country: China
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]